### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by omxpro** [akuhnet/wqemu#1]
When the thing fails and we run the start stuff again it downloads that 5gb file again and again btw you should make a rdp with ngrok for termux and UserLAnd

**Comment by omxpro** [comment]
RDP Address:
curl: (7) Failed to connect to 127.0.0.1 port 4040 after 3 ms: Connection refused
====================================
Username: akuh                                    Password: Akuh.Net
====================================
====================================
Keep supporting akuh.net, thank you               You Got Free RDP now
Wait 2 minute to finish bot
You can close this tab
RDP runs for 50 hours
====================================

**Comment by akuhnet** [comment]
it's a problem in ngrok token, reset token and repeat

**Comment by omxpro** [comment]
Ok

**Comment by omxpro** [comment]
Same error on like 2nd ngrok token

**Comment by omxpro** [comment]
Btw what's the method for https://github.com/akuhnet/wqemu/blob/main/w10x64kvm.sh

**Comment by omxpro** [comment]
@akuhnet ^^

**Comment by akuhnet** [comment]
> Btw what's the method for https://github.com/akuhnet/wqemu/blob/main/w10x64kvm.sh

use katacoda or azure terminal,, but not fix

**Comment by akuhnet** [comment]
> Same error on like 2nd ngrok token

can you give me link you used ? i will check it

**Comment by omxpro** [comment]
clear
sudo su
wget -O w10x64.sh https://bit.ly/windows10x64gitpod
chmod +x w10x64.sh
./w10x64.sh

**Comment by omxpro** [comment]
It's the gitpod one

**Comment by akuhnet** [comment]
ok done
